### ISSUE TITLE
I18n cleanup

### ISSUE THREAD

**Issue by juddus** [HandsFree/beaconing-teacher-ui#153]
## Issue summary
Some phrases aren't needed or are similar. Unique prefixes aren't needed in most cases

**Comment by felixangell** [comment]
This is what I'm not sure about since language is contextual. So you could compress/optimize this by removing things if you are 100% sure nothing will change... but say in the future we change some translation from `calendar` to `my calendar`, where we have something like `felix's {calendar}` it becomes `felix's {my calendar}`.
